#!/usr/bin/env bash

acct_available() { have nft; }

acct_name() { printf 'acct_%s' "$(printf '%s' "$1" | tr -c 'a-zA-Z0-9' '_')"; }

acct_bootstrap() {
    acct_available || return 1
    nft list table inet "$ACCT_TABLE" >/dev/null 2>&1 && return 0
    nft add table inet "$ACCT_TABLE" 2>/dev/null || return 1
    nft add chain inet "$ACCT_TABLE" out \
        '{ type filter hook output priority -300 ; policy accept ; }' 2>/dev/null || return 1
    return 0
}

acct_add() {
    local user="$1" uid name
    acct_available || return 0
    acct_bootstrap || return 0
    uid=$(id -u "$user" 2>/dev/null) || return 0
    name=$(acct_name "$user")
    nft list counter inet "$ACCT_TABLE" "$name" >/dev/null 2>&1 || \
        nft add counter inet "$ACCT_TABLE" "$name" 2>/dev/null
    nft list chain inet "$ACCT_TABLE" out 2>/dev/null | grep -q "\"$name\"" && return 0
    nft add rule inet "$ACCT_TABLE" out meta skuid "$uid" counter name "\"$name\"" 2>/dev/null
}

acct_del() {
    local user="$1" name handle
    acct_available || return 0
    name=$(acct_name "$user")
    handle=$(nft -a list chain inet "$ACCT_TABLE" out 2>/dev/null | \
             awk -v n="\"$name\"" '$0 ~ n {print $NF; exit}')
    [ -n "$handle" ] && nft delete rule inet "$ACCT_TABLE" out handle "$handle" 2>/dev/null
    nft delete counter inet "$ACCT_TABLE" "$name" 2>/dev/null
    return 0
}

acct_read() {
    local name="$1"
    nft list counter inet "$ACCT_TABLE" "$name" 2>/dev/null | \
        awk '/bytes/ {print $4; exit}'
}

acct_reset() {
    nft reset counter inet "$ACCT_TABLE" "$1" >/dev/null 2>&1 || true
}

acct_sync() {
    local user name delta used
    acct_available || return 0
    acct_bootstrap || return 0
    while IFS= read -r user; do
        [ -n "$user" ] || continue
        name=$(acct_name "$user")
        delta=$(acct_read "$name")
        [ -n "$delta" ] || { acct_add "$user"; continue; }
        [ "$delta" = "0" ] && continue
        used=$(db_used "$user")
        is_number "$used" || used=0
        db_update "$user" 6 "$(( used + delta ))"
        acct_reset "$name"
    done < <(db_names)
}

acct_repair() {
    local user
    acct_bootstrap || { warn "nftables is unavailable, traffic accounting disabled."; return 1; }
    while IFS= read -r user; do
        [ -n "$user" ] || continue
        acct_add "$user"
    done < <(db_names)
    ok "Accounting rules rebuilt."
}

session_peers() {
    local user="$1" pids pid
    pids=$(pgrep -x sshd -u "$user" 2>/dev/null | tr '\n' ',' | sed 's/,$//')
    [ -n "$pids" ] || return 0
    for pid in ${pids//,/ }; do
        ss -Hntp state established 2>/dev/null | \
            awk -v p="pid=$pid," '$0 ~ p {split($4, a, ":"); print $4}' | head -n 1
    done
}

online_view() {
    local user count peer since
    heading "Live sessions"
    printf '  %-16s %-8s %-24s %s\n' "USER" "COUNT" "PEER" "UPTIME"
    rule
    local any=0
    while IFS= read -r user; do
        [ -n "$user" ] || continue
        count=$(user_sessions "$user")
        [ "$count" -gt 0 ] || continue
        any=1
        peer=$(ss -Hntp state established 2>/dev/null | \
               awk -v u="$user" '/sshd/ {print $5}' | head -n 1)
        since=$(ps -o etime= -u "$user" 2>/dev/null | head -n 1 | tr -d ' ')
        printf '  %-16s %-8s %-24s %s\n' "$user" "$count" "${peer:-n/a}" "${since:-n/a}"
    done < <(db_names)
    [ "$any" = "0" ] && plain "${C_GREY}Nobody is connected right now.${C_RESET}"
    blank
}

traffic_view() {
    local user used quota total=0
    acct_sync
    heading "Traffic report"
    printf '  %-16s %-14s %-14s %s\n' "USER" "USED" "QUOTA" "REMAINING"
    rule
    while IFS= read -r user; do
        [ -n "$user" ] || continue
        used=$(db_used "$user"); is_number "$used" || used=0
        quota=$(db_quota "$user"); is_number "$quota" || quota=0
        total=$(( total + used ))
        if [ "$quota" = "0" ]; then
            printf '  %-16s %-14s %-14s %s\n' "$user" "$(human_bytes "$used")" "unlimited" "-"
        else
            printf '  %-16s %-14s %-14s %s\n' "$user" "$(human_bytes "$used")" \
                "$(human_bytes "$quota")" "$(human_bytes "$(( quota > used ? quota - used : 0 ))")"
        fi
    done < <(db_names)
    rule
    field "Total accounted" "$(human_bytes "$total")"
    plain "${C_GREY}Counters measure traffic generated by each tunnel session.${C_RESET}"
    blank
}

enforce_expiry() {
    local user expires
    while IFS= read -r user; do
        [ -n "$user" ] || continue
        expires=$(db_expires "$user")
        if is_expired "$expires" && [ "$(db_state "$user")" != "locked" ]; then
            user_lock "$user"
            log_event "auto lock $user reason=expired"
        fi
    done < <(db_names)
}

enforce_quota() {
    local user used quota
    while IFS= read -r user; do
        [ -n "$user" ] || continue
        quota=$(db_quota "$user"); is_number "$quota" || continue
        [ "$quota" = "0" ] && continue
        used=$(db_used "$user"); is_number "$used" || continue
        if [ "$used" -ge "$quota" ] && [ "$(db_state "$user")" != "locked" ]; then
            user_lock "$user"
            log_event "auto lock $user reason=quota"
        fi
    done < <(db_names)
}

enforce_connections() {
    local user limit count victim
    while IFS= read -r user; do
        [ -n "$user" ] || continue
        limit=$(db_maxconn "$user"); is_number "$limit" || continue
        [ "$limit" -le 0 ] && continue
        count=$(user_sessions "$user")
        while [ "$count" -gt "$limit" ]; do
            victim=$(pgrep -x sshd -u "$user" -n 2>/dev/null)
            [ -n "$victim" ] || break
            kill -KILL "$victim" 2>/dev/null || break
            log_event "dropped extra session pid=$victim user=$user limit=$limit"
            count=$(( count - 1 ))
        done
    done < <(db_names)
}

menu_traffic() {
    local choice user
    while :; do
        banner
        traffic_view
        plain "1) Refresh          3) Reset counter for one user"
        plain "2) Rebuild rules    4) Reset every counter"
        plain "0) Back"
        blank
        choice=$(ask "Select" "")
        case "$choice" in
            1) : ;;
            2) acct_repair; pause ;;
            3) user=$(pick_user) && { db_update "$user" 6 0; acct_reset "$(acct_name "$user")"; ok "Counter cleared."; }
               pause ;;
            4) if ask_yes "Clear traffic history for every account?" "n"; then
                   while IFS= read -r user; do
                       [ -n "$user" ] || continue
                       db_update "$user" 6 0
                       acct_reset "$(acct_name "$user")"
                   done < <(db_names)
                   ok "All counters cleared."
               fi
               pause ;;
            0|q|"") return ;;
            *) bad "Unknown option."; sleep 1 ;;
        esac
    done
}

menu_connections() {
    local choice user
    while :; do
        banner
        online_view
        plain "1) Refresh    2) Disconnect a user    0) Back"
        blank
        choice=$(ask "Select" "")
        case "$choice" in
            1) : ;;
            2) user=$(pick_user) && { kill_sessions "$user"; ok "$user disconnected."; }
               pause ;;
            0|q|"") return ;;
            *) bad "Unknown option."; sleep 1 ;;
        esac
    done
}
